
const SGC_DATA = {
    // =================================================================
    // CORE PAGE CONTENT
    // =================================================================
    "page_index": {
        "title": "NUH Clinical Pathology Shared Governance",
        "intro": "Discover our projects, read our latest news, and find helpful resources from the Nottingham University Hospitals Clinical Pathology team.",
        "cards": [
            { "icon": "clipboard", "title": "Our Projects", "description": "See the initiatives we're working on.", "url": "projects.html" },
            { "icon": "play-circle", "title": "Pathology Games", "description": "Test your knowledge with our fun, interactive games.", "url": "games.html" },
            { "icon": "tool", "title": "Helpful Tools", "description": "Practical utilities to help with day-to-day tasks.", "url": "helpful_tools.html" },
            { "icon": "file-text", "title": "Newsletters", "description": "Catch up on the latest news from the council.", "url": "newsletters.html" },
            { "icon": "users", "title": "About Us", "description": "Learn about our council and what we do.", "url": "about.html" },
            { "icon": "book-open", "title": "Learning Links", "description": "Useful resources for professional development.", "url": "links.html" },
            { "icon": "instagram", "title": "Social Media", "description": "Videos promoting our role as Biomedical Scientists.", "url": "social.html" },
            { "icon": "send", "title": "Suggestions", "description": "Have an idea for a project? Let us know.", "url": "contact.html" }
        ]
    },
    "page_about": {
        "title": "About Us & The Council",
        "shared_governance_title": "What is Shared Governance?",
        "shared_governance_intro": "Shared Governance is a model of empowerment that gives staff a direct voice in the decisions that affect their working lives and the quality of patient care. It moves away from traditional top-down management, creating a partnership between frontline staff and leadership.",
        "council_mission": "Through councils like ours, team members can take ownership of clinical practice, shape policies, and drive improvements from the ground up. We are proud to be the first non-patient-facing, Pathology-specific Shared Governance Council in the UK, pioneering this approach to enhance our services and empower our dedicated scientific and support staff."
    },
    "page_contact": {
        "title": "Have a Suggestion?",
        "intro_text": "Your ideas are important to us. If you have a suggestion for a new project or an improvement, we'd love to hear from you. Please get in touch with the council chair.",
        "chair_name": "Michael Ellingham",
        "chair_email": "michael.ellingham@nhs.net"
    },
    "page_projects_landing": {
        "title": "Our Projects",
        "projects": [
            { "title": "Patient Interviews & Tours", "description": "Learn more about our patient-focused initiatives.", "url": "patient_interviews.html", "image": "interview.jpeg" },
            { "title": "Laboratory Video Tours", "description": "Discover our video series for wards and GPs.", "url": "video_tours.html", "image": "lab.jpg" },
            { "title": "Garden Project", "description": "See how we're creating a space for wellbeing.", "url": "garden_project.html", "image": "garden.jpg" }
        ]
    },
    "page_patient_interviews": {
        "title": "Patient Interviews & Tours",
        "intro": "This project aims to bridge the gap between the laboratory and the patient experience. By sharing patient stories and providing lab tours, we can better understand the impact of our work and find new ways to improve patient care.",
        "interview_title": "Patient Interviews",
        "tours_title": "Harvey's Lab Tours",
        "tours_intro": "Here are some prior tours provided by the laboratory via Harvey's Gang (now Harvey's Lab Tours).",
        "harvey_links": [
            { "title": "Young patient becomes a ‘trainee biomedical scientist’ (Nov 2019)", "description": "Read about seven-year-old Evie's tour of the labs at QMC.", "url": "https://www.nuh.nhs.uk/news/young-patient-becomes-a-trainee-biomedical-scientist-at-queens-medical-centre-3549/" },
            { "title": "Daughter with rare condition can be 'happy and confident' (Nov 2023)", "description": "A recent tour for a young girl to help her understand her treatment.", "url": "https://www.nottinghampost.com/news/local-news/rare-condition-daughter-can-happy-8946245" },
            { "title": "Pathologists help 13-year old boy overcome fear of blood tests (May 2018)", "description": "The story of the very first Harvey's Gang tour at NUH.", "url": "https://www.nuh.nhs.uk/news/pathologists-at-nuh-help-13year-old-boy-with-rare-illness-overcome-fear-of-blood-tests-2728/" }
        ]
    },
    "page_nikki_story": {
        "title": "Nikki Fretwell's Story",
        "article_title": "Newsletter Article",
        "content_html": "<p class=\"font-bold text-lg\">Dialysis is something I do. It doesn’t define me.</p><p>Recently, pathology had the privilege of meeting a phenomenal woman. Her name is Nikki Fretwell. She is a mother, a musician, a gym lover and has even presented her own radio show. She spent 22 years in education and now speaks at renal conferences, and supports other people with kidney disease. As a renal patient herself, Nikki was interested to know of potential effects due to delay of sample receipt and processing, for blood samples taken at home. It was especially important to her, to know if the laboratory staff were aware of the importance of her blood results as a renal patient, and that we understood the how the results would affect her, and other renal patients. Especially considering that she dialyses at home, herself. For Nikki, she must tailor her dialysis dependant on the monthly blood test results she receives: Pre and post dialysis bloods reflect how well she dialyses. Everything must be assessed via blood tests as no urine sample is available for analysis. (Some dialysis patients do not produce urine.)</p><img src=\"nikki-fistula.jpg\" onerror=\"this.onerror=null;this.src='https://placehold.co/600x400/e0e0e0/808080?text=Image+Not+Found';\" alt=\"A fistula in Nikki's arm, which she uses for dialysis\" class=\"my-6 rounded-lg shadow-md mx-auto w-full max-w-md\"><p>All blood samples come from a fistula in Nikki’s arm- she takes the blood herself! The fistula is her lifeline. There is no other access to blood, as her veins are brittle and calcified. So, she protects her lifeline and takes her own blood. She told us ‘‘Nobody else is allowed to come near me with a needle’’</p><p>Nikki is one of the longest surviving non-transplanted dialysis patients in the UK, having been on dialysis for 34 years!</p><p>At only 17, she started to experience symptoms which were affecting her quality of life, and was later diagnosed with the autoimmune disease, Focal segmental glomerulosclerosis. FSGS attacks the nephrons in the kidneys. So, at 17, she was put on the transplant list. Three years of pain and difficulty, medications and missing out on teenage life, at the age of 19, she asked, “Will I be better off on dialysis?” and after advocating for herself, things started to improve. She has had to advocate for herself again and again and again. She is the reason she is still so strong all these years later.</p><blockquote>\"You have to know your own condition, and you have to be able to advocate for yourself in a way that other people will listen to. So that is a constant thing, and it's very common in dialysis patients, kidney patients in general, that feel they are unheard a lot of the time.\"</blockquote><p>During her time dialysing at the hospital, She would make the effort to ask the nurses, scientific and medical questions, to better understand her condition and learn as much as she could from them. There wasn’t the access to the internet or google then. And you spend a lot of time with these nurses if you’re having dialysis at the hospital. Hospital dialysis is 3 times a week, every week, forever, or until you get a transplant. There is no time off.</p><blockquote>\"dialysis patients spend a lot of their time waiting. Waiting for hospital appointments, waiting for GP appointments, waiting for transport to and from dialysis, waiting for a machine, waiting for a transplant. We spend a lot of time waiting, and then you sit on the machine for four hours and wait until the four hours is over.\"</blockquote><p>Home dialysis has offered some freedom by getting rid of those strict time restrictions and has allowed Nikki to not only work but do all kinds of hobbies and activities. She has been dialysing overnight at home since 2014, which has given her more independence and control over her life.</p><p>At just 21, she learned to put her own needles in so she could dialyse at home. Not too long after this, she fell pregnant. Nobody in the world, receiving dialysis, had ever had a baby. The very few people who had got pregnant, sadly never had a successful birth. She told us that \"Dialysis patients, generally speaking, don't get pregnant. Very often they have no menstrual cycle, and even if they do, their bodies are just not able to sustain any pregnancy, if they've got creatinine of over 300.\"</p><p>Her son is now in his 30s! Even with the odds stacked against her, she carried her baby until 7 months, and he was born weighing just under two pounds.</p><h3>So… why did Nikki not have a transplant?</h3><p>She did! After almost 20 years of being on the transplant list, waiting for a rare tissue type match, Nikki had a kidney transplant. Unfortunately, however, it is not like it is portrayed on TV, where it’s a complete fix and you just carry on with life with a spring in your step. There are difficulties when things go well and unfortunately things don’t always even go well. Nikki faced complications and after 5 months the kidney was removed. She made the decision not to go back on the transplant list.</p><p>Her take home message is that long term dialysis should be promoted. Everybody seems to think that a transplant is the only next step. She wants people to know not to put their life on pause waiting for a transplant and has proven that you can absolutely live without one.</p><img src=\"nikki-quote.jpg\" onerror=\"this.onerror=null;this.src='https://placehold.co/800x200/e0e0e0/808080?text=Image+Not+Found';\" alt=\"A quote from Nikki's interview about not waiting for a transplant\" class=\"my-6 rounded-lg shadow-md mx-auto w-full\"><p>If you want to know more about this incredible woman, please keep a look out for the interview material available soon: Question and answers will be shared from our interview with Nikki, with an accompanying video.</p>"
    },
    "page_video_tours": {
        "title": "Laboratory Video Tours",
        "intro": "We're curating a series of videos for each department in Clinical Pathology to teach the wards and GPs what we do and what they can do to help us improve patient care. These short, engaging videos will cover key aspects of the pathology process, from sample collection to result interpretation, providing a valuable educational resource for clinical staff.",
        "chemistry_video_url": "https://www.canva.com/design/DAGrMNYRfp8/pHyUmUFeWLuQibuvzMzubg/view?embed"
    },
    "page_social": {
        "title": "Social Media Showcase",
        "intro": "We're looking for staff to help us create a series of videos for all departments, promoting our role and what we do in the lab. Please send us your videos to help kick-start this exciting project!",
        "submit_email": "mailto:michael.ellingham@nhs.net?subject=SGC%20Video%20Submission",
        "videos": [
            { "title": "A Day in the Life (TikTok)", "description": "A great short video showcasing the work of Biomedical Scientists.", "url": "https://vm.tiktok.com/ZNdBGuPcg/", "thumbnail": "tiktok-thumbnail.jpg", "type": "link" },
            { "title": "\"Biomedical Science is like medicine but easier\"", "description": "A Q&A short addressing this common misconception.", "url": "https://www.youtube.com/embed/4AI7y--kvs0", "type": "embed" },
            { "title": "All about blood smears (Part 1)", "description": "A quick and informative look at creating blood smears in the lab.", "url": "https://www.youtube.com/embed/vjMLVGA2JuU", "type": "embed" },
            { "title": "Q&A with a BMS Apprentice", "description": "An insightful Q&A session with an NHS apprentice Biomedical Scientist.", "url": "https://www.youtube.com/embed/Z2yLTLG2xN8", "type": "embed" }
        ]
    },
    "page_sustainability_corner": {
        "title": "Resource & Sustainability Corner",
        "intro": "Learn about how we can use our resources more mindfully, reduce waste, and improve efficiency. Small changes can make a big difference.",
        "links": [
            { "icon": "truck", "title": "The Journey of a Sample", "description": "An insight into the resources and costs involved in every step of the sample pathway.", "url": "journey_of_a_sample.html" },
            { "icon": "plus-circle", "title": "The Power of the Add-On Test", "description": "A guide explaining which tests can be added to existing samples, avoiding unnecessary re-bleeds.", "url": "add_on_guide.html" },
            { "icon": "trash-2", "title": "Waste Management & Costs", "description": "Learn about the correct disposal of laboratory waste and the surprising costs involved.", "url": "waste_management.html" }
        ]
    },
    "page_journey_of_a_sample": {
        "title": "The Journey of a Sample",
        "intro": "From the patient's arm to the final report, every sample consumes valuable resources. Understanding this journey helps us appreciate the importance of getting it right first time.",
        "steps": [
            { "icon": "user-plus", "title": "Step 1: The Request & Collection", "description": "The process begins with a clinical need. A request is made, and a trained phlebotomist collects the sample from the patient.", "resources": ["Staff Time: Phlebotomist/Nurse time, Clerical time.", "Consumables: Needle, tube holder, vacutainer tube(s), alcohol wipe, gauze, plaster, transport bag."] },
            { "icon": "truck", "title": "Step 2: Transport to the Lab", "description": "The sample must be transported safely and quickly to the laboratory to ensure its integrity.", "resources": ["Pneumatic Tube System: Significant electrical energy consumption.", "Portering Service: Staff time and wages.", "Van Transport (for GP practices): Fuel, vehicle maintenance, driver's time."] },
            { "icon": "log-in", "title": "Step 3: Laboratory Reception & Preparation", "description": "The sample arrives, is checked against the request, and booked into the Laboratory Information Management System (LIMS).", "resources": ["Staff Time: MLA/AP time for booking-in and sorting.", "Electricity: Power for centrifuges (for serum/plasma), computers, and barcode scanners.", "Asset Use: High-speed centrifuges are expensive assets that require regular maintenance."] },
            { "icon": "cpu", "title": "Step 4: Analysis", "description": "The sample is processed on a highly complex, automated analyser.", "resources": ["High-Value Asset: Analysers cost tens to hundreds of thousands of pounds and have expensive service contracts.", "Reagents & Consumables: Every test uses specific, costly reagents, diluents, and cleaning fluids.", "Quality Control: QC material must be run every day to ensure accuracy, consuming further reagents.", "Electricity & Water: Analysers are significant consumers of power and purified water.", "Estimated Cost per FBC/U&E: ~£1.00 - £3.00 in direct analytical costs."] },
            { "icon": "check-square", "title": "Step 5: Validation & Reporting", "description": "A qualified Biomedical Scientist reviews the result, checks for errors, and validates it. Abnormal results may require further interpretation or referral.", "resources": ["Highly Skilled Staff Time: The expertise of a registered BMS is essential for ensuring the quality and safety of every result.", "IT Infrastructure: Servers and software (LIMS) are needed to manage and store millions of patient results securely."] },
            { "icon": "archive", "title": "Step 6: Storage & Disposal", "description": "After analysis, samples are stored for a set period in large, refrigerated units before being disposed of as clinical waste.", "resources": ["Cold Storage: Walk-in fridges consume a large amount of electricity 24/7 to keep samples viable for add-on tests.", "Clinical Waste Disposal: Disposing of thousands of samples per day is a major operational cost.", "Cost of Waste: A single bin of clinical waste can cost **over £20** to dispose of correctly."] }
        ],
        "summary": "When you combine consumables, staff time, transport, energy, and waste, the true cost of a single \"routine\" blood test is far more than just the reagents. Every rejected sample that requires a redraw multiplies this cost. **Getting it right first time matters.**"
    },
    "page_waste_management": {
        "title": "A Guide to Waste Management",
        "intro": "Helping Pathology save money and protect the environment.",
        "chart_title": "The True Cost of Our Bins",
        "chart_intro": "Using the wrong bin is one of the biggest sources of preventable cost in the Trust. The price to dispose of waste varies dramatically depending on the stream. This chart shows the average cost to dispose of one tonne of waste, based on NUH policy.",
        "streams": [
            { "title": "Waste for Incineration", "icon": "alert-octagon", "bag": "Yellow Bag / Yellow-lidded Sharps Bin", "color": "yellow-600", "description": "This stream is for waste that <strong>must be incinerated</strong> due to chemical or medicinal contamination. This is our most expensive waste stream and should be used with care.", "costPerTonne": 600, "costPerBin": "£4 - £6", "examples": ["Waste contaminated with chemicals or medicines (except cytotoxic).", "All sharps (needles, slides, broken glass from lab).", "Known highly infectious laboratory waste.", "Blood gas analyser cartridges."] },
            { "title": "Infectious Clinical Waste", "icon": "biohazard", "bag": "Orange Bag", "color": "orange-600", "description": "For waste contaminated with blood or other bodily fluids that is known or believed to be infectious. This waste is sent for alternative treatment (e.g., autoclaving) to render it safe before disposal.", "costPerTonne": 420, "costPerBin": "£3 - £4", "examples": ["Used sample tubes (EDTA, Serum, Citrate etc.)", "Contaminated gloves, aprons, and other PPE.", "Blood product packaging.", "Used sample swabs and plastic pasteurs.", "Contaminated bench roll and consumables."] },
            { "title": "Offensive Waste", "icon": "wind", "bag": "Tiger Stripe Bag (Yellow with Black Stripes)", "color": "yellow-800", "description": "For non-infectious waste that may be unpleasant (e.g., contains body fluids but from a non-infectious source). A much cheaper alternative to orange/yellow streams.", "costPerTonne": 300, "costPerBin": "£2 - £3", "examples": ["Used PPE (gloves, masks) from non-infectious areas.", "Non-infectious incontinence pads.", "Non-infectious wound dressings.", "Empty, non-contaminated urine containers."] },
            { "title": "General / 'Black Bag' Waste", "icon": "archive", "bag": "Black Bag", "color": "gray-800", "description": "This is for general, non-clinical waste. Using this correctly for non-contaminated items is the most cost-effective and environmentally friendly option.", "costPerTonne": 160, "costPerBin": "Less than £1.50", "examples": ["Paper towels and outer cardboard packaging.", "Non-contaminated stationery.", "Food wrappers and drink cans.", "Uncontaminated plastic packaging."] },
            { "title": "Recycling & Cardboard", "icon": "recycle", "bag": "Clear Bag / Designated Cardboard Bin", "color": "green-600", "description": "For clean, non-contaminated recyclable materials. Cardboard should be flattened and placed in designated large bins.", "costPerTonne": 40, "costPerBin": "Less than £0.50", "examples": ["Clean plastic bottles and cans.", "Non-confidential paper and office waste.", "Flattened reagent and delivery boxes.", "Newspapers and magazines."] }
        ],
        "summary": "Placing a single non-infectious, non-contaminated item in a yellow stream bin means the whole bin must be incinerated at a high cost. Every item placed in the correct bin makes a significant financial and environmental difference. Think before you throw!"
    },

    // =================================================================
    // DATA LISTS
    // =================================================================
    "members": [
        { "name": "Michael Ellingham", "department": "Haematology & Blood Transfusion", "email": "Michael.ellingham@nhs.net", "image_url": "placeholder.jpg" },
        { "name": "Katarzyna Fijalkowska", "department": "Haematology & Blood Transfusion", "email": "katarzyna.fijalkowska@nhs.net", "image_url": "placeholder.jpg" },
        { "name": "Akwasi Boakye", "department": "Immunology", "email": "akwasi.boakye1@nhs.net", "image_url": "placeholder.jpg" },
        { "name": "Yasmin Dixon", "department": "Chemistry", "email": "yasmin.dixon1@nhs.net", "image_url": "placeholder.jpg" },
        { "name": "Matthew Rodgers", "department": "Chemistry", "email": "matthew.rodgers6@nhs.net", "image_url": "placeholder.jpg" }
    ],
    "newsletters": [
        { "title": "July 2025 Edition", "url": "https://www.canva.com/design/DAGq_W5r-H4/7ZHZKr-ctFrh4vkM6JyN_g/view" },
        { "title": "June 2025 Edition", "url": "https://www.canva.com/design/DAGnXoAq70Y/0VKC3AAIqPUdaLLZ3cpQUg/view" },
        { "title": "May 2025 Edition", "url": "https://www.canva.com/design/DAGj3M0ceJ4/nLv3uC_Jojrf20YVExh8Vw/view" },
        { "title": "April 2025 Edition", "url": "https://www.canva.com/design/DAGhotuowcw/bUjeV9GXeNrwuFZTfrObjA/view" },
        { "title": "March 2025 Edition", "url": "https://www.canva.com/design/DAGecEbcDF4/bbbGy79e_uK0gRLLYJa4nA/view" },
        { "title": "January 2025 Edition", "url": "https://www.canva.com/design/DAGSvAh8E6I/b4ZBT3LhYVKWDxoh-OYN5g/view" }
    ],
    "learning_links": {
        "general": [
            { "name": "IBMS", "url": "https://www.ibms.org/home/", "description": "The Institute of Biomedical Science - our professional body." },
            { "name": "HCPC", "url": "https://www.hcpc-uk.org/", "description": "The Health and Care Professions Council - our regulator." }
        ],
        "haematology": [
            { "name": "British Society for Haematology", "url": "https://b-s-h.org.uk/", "description": "Guidelines, research and education for haematology." }
        ],
        "transfusion": [
            { "name": "Transfusion Guidelines (JPAC)", "url": "https://www.transfusionguidelines.org/", "description": "The official UK guidelines for blood transfusion services." }
        ],
        "chemistry": [
            { "name": "Association for Laboratory Medicine", "url": "https://labmed.org.uk/", "description": "Formerly the ACB, a key professional body for the field." }
        ],
        "immunology": [
            { "name": "British Society for Immunology", "url": "https://www.immunology.org/", "description": "Representing scientists and clinicians in immunology." }
        ]
    },

    // =================================================================
    // TOOLS & GUIDES
    // =================================================================
    "tool_add_on_guide": {
        "title": "The Power of the Add-On Test",
        "intro": "A guide to sample stability for add-on requests. Avoiding a re-bleed saves time, resources, and improves the patient experience.",
        "patient_impact_title": "Better for the Patient",
        "patient_impact_text": "Every unnecessary venepuncture is an uncomfortable experience for the patient. For those with difficult venous access, children, or needle-phobic individuals, avoiding a redraw significantly improves their quality of care and perception of our service.",
        "trust_impact_title": "Better for the Trust",
        "trust_impact_text": "Each blood draw has a cost. While it seems small, the cumulative cost of staff time (phlebotomist, porter, lab staff) and consumables (needle, holder, tubes, bag) is estimated at **£5 - £7 per collection**. Using an existing sample is a direct and simple way to save money.",
        "biochemistry_data": [
            { "test": "Amylase", "tube": "Serum (Gold Top)", "stability": "7 days" }
        ],
        "haematology_data": [
            { "test": "APTT (for Heparin monitoring)", "tube": "Citrate (Blue Top)", "stability": "2 hours" }
        ]
    },
    "tool_cell_counter": {
        "title": "Manual Differential Counter",
        "intro": "Use your keyboard number keys to count cells. Enter the patient's total WBC to calculate absolute values.",
        "cell_groups": {
            "wbc": { "1": "Neutrophils", "2": "Lymphocytes", "3": "Monocytes", "4": "Eosinophils", "5": "Basophils" },
            "other": { "6": "Metamyelocytes", "7": "Myelocytes", "8": "Promyelocytes", "9": "Blasts", ".": "Plasma Cells", "0": "NRBCs" }
        }
    },
    "tool_glossary": {
        "haem": [
            { "term": "Acanthocyte (Spur Cell)", "definition": "An erythrocyte (red blood cell) with a few, irregularly spaced spikes of varying length. Associated with severe liver disease." }
        ],
        "trans": [
            { "term": "A, B, O Antigens", "definition": "Carbohydrate structures on the surface of red blood cells that determine the ABO blood group." }
        ],
        "chem": [
            { "term": "Acid-Base Balance", "definition": "The mechanism by which the body maintains the pH of its fluids within a narrow, normal range. Primarily involves the lungs and kidneys." }
        ],
        "imm": [
            { "term": "Adjuvant", "definition": "A substance that enhances the body's immune response to an antigen, often included in vaccines." }
        ]
    },
    "tool_interpretive_guide": {
        "title": "Interpretive Comment Guide",
        "intro": "Search for a term to understand its clinical significance and appropriate next steps.",
        "haem": [
            { "term": "Leucoerythroblastic Picture", "meaning": "The presence of immature red cells (Nucleated Red Blood Cells) and immature white cells (e.g., myelocytes, metamyelocytes) in the peripheral blood. Teardrop-shaped red cells are often also present.", "causes": "Indicates significant bone marrow disturbance. Common causes include myelofibrosis, metastatic cancer infiltrating the marrow, severe haemolysis, or overwhelming infection (sepsis).", "nextSteps": "This is a significant finding requiring urgent clinical correlation. Review previous haematology results. A bone marrow biopsy is often indicated to determine the underlying cause. Refer to haematology for review." }
        ],
        "coag": [
            { "term": "Prolonged APTT (@PAPT)", "meaning": "The activated partial thromboplastin time, a measure of the intrinsic coagulation pathway, is longer than the reference range.", "causes": "Common causes include heparin therapy, presence of a lupus anticoagulant, clotting factor deficiencies (e.g., Haemophilia A/B), liver disease, or DIC.", "nextSteps": "Suggest repeat in the first instance to rule out pre-analytical error. Correlate with clinical picture (bleeding?) and medication history (heparin?). Further tests (e.g., mixing studies, factor assays) may follow if confirmed." }
        ],
        "haemoglobinopathy": [
            { "term": "No Abnormality Detected (@HNON / @HNOA)", "meaning": "The analysis shows a normal haemoglobin pattern.", "causes": "Normal genetic makeup for haemoglobin.", "nextSteps": "No evidence of sickle haemoglobin or other common haemoglobin variant or of thalassaemia. For antenatal screening, testing of the baby’s biological father is not required based on this result." }
        ]
    },
    "tool_lipaemia_calculator": {
        "title": "Lipaemia Correction Calculator",
        "intro": "Calculates a corrected Haemoglobin and red cell indices for a lipaemic FBC sample as per the NUH protocol."
    },
    "tool_pre_analytical_query": {
        "title": "Pre-analytical Query Tool",
        "intro": "Search for any test in the directory to view its specific sample requirements and turnaround times.",
        "test_requirements": [
            { "name": "y-Glutamyl Transferase (GGT)", "lab": "Chemistry", "reqs": ["Sample: 5mL SST/serum", "Turnaround: 60 mins (ED), 180 mins (Inpatient), 24 hours (GP)"] },
            { "name": "17- OH-progesterone (17-OHP)", "lab": "Other (Referred)", "reqs": ["Sample: Plain serum (red top) ONLY", "Turnaround: 14 days"] }
        ]
    },
    "tool_rejection_troubleshooter": {
        "title": "Sample Rejection Troubleshooter",
        "intro": "A practical guide to understanding and preventing common sample collection errors.",
        "reasons": {
            "haemolysed": { "title": "Haemolysed Sample", "icon": "droplet", "causes": ["Difficult venepuncture (e.g., probing for a vein, slow draw)."], "prevention": ["Ensure a smooth, clean venepuncture with a good blood flow."], "impact": "Haemolysis releases intracellular components into the plasma/serum..." },
            "clotted": { "title": "Clotted Sample", "icon": "grid", "causes": ["Insufficient or delayed mixing of anticoagulant tubes (e.g., EDTA, Citrate)."], "prevention": ["Gently invert anticoagulant tubes 8-10 times immediately after collection."], "impact": "Clots consume platelets and clotting factors..." }
        }
    },

    // =================================================================
    // GAMES
    // =================================================================
    "game_coagulation": {
        "title": "Coagulation Cascade Challenge",
        "intro": "Drag and drop the factors from the bank into their correct positions in the cascade.",
        "factors": [ { "id": "VIIa", "name": "Factor VIIa" }, { "id": "IXa", "name": "Factor IXa" } ]
    },
    "game_compatibility": {
        "title": "Blood Group BATTLE",
        "intro": "A patient needs blood. Is the unit compatible? Make the right call!",
        "blood_groups": ["O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+"],
        "compatibility_matrix": { "O-": ["O-"], "O+": ["O-", "O+"] }
    },
    "game_disease_association": {
        "title": "Antibody & Disease Association",
        "intro": "Test your knowledge of autoimmune serology. Select the correct match for the given item.",
        "associations": [ { "antibody": "Anti-dsDNA", "disease": "Systemic Lupus Erythematosus" } ]
    },
    "game_chemistry": {
        "title": "Clinical Chemistry Case Challenge",
        "intro": "Analyse the patient's case notes and biochemistry results to determine the most likely diagnosis.",
        "cases": [ { "scenario": "A 68-year-old man presents to A&E...", "answer": "Acute Pancreatitis" } ]
    },
    "game_fbc_challenge": {
        "title": "Name That Condition",
        "intro": "Analyse the results and clinical note to identify the most likely condition.",
        "scenarios": [ { "condition": "Iron Deficiency Anaemia", "clinicalNote": "Patient presents with fatigue...", "explanation": "Lack of iron impairs haemoglobin synthesis..." } ]
    },
    "game_haem_morphology": {
        "title": "Morphology Mastermind",
        "intro": "Read the description of a haematological feature and select the correct term.",
        "pairs": [ { "term": "Red Blood Cell", "description": "A non-nucleated, biconcave disc...", "category": "RBC Basic" } ]
    },
    "game_immunology_wordsearch": {
        "title": "Immunology Word Search",
        "intro": "Find the immunology terms hidden in the grid. Click and drag to select a word.",
        "word_list": ["ADRENAL", "ALLERGY", "ANCA", "ANTIBODY", "ANTIGEN"]
    },
    "game_lab_discussions": {
        "title": "Lab Questions",
        "questions": [ "Is a toastie a sandwich?", 
            "What are your top 5 90s movies?",
        "What would be your three dream festival headliners?",
                "If you had to eat one sandwich for the rest of your life, what would it be?",
                "Is Die Hard a Christmas film?",
                "What would you cook on Come Dine With Me?",
                "If you could ask three questions to see if you'd be friends with someone, what would you ask?",
                "Do you have any ghost stories?",
                "What's your most mundane celebrity encounter?",
              "Would you rather have a middle finger that could travel time, despite being connected to you in the present, or an armpit that can dispense talc?",
                "If you could be a piece of furniture, what would you be?",
                "As you lay dying, which celebrity would you want to stroke your hair?",
                "If you had to replace your hands with two non-hand objects, what would they be?",
                "Would you rather always have to sing what you say, or always have to dance where you go?",
                "If you could instantly become fluent in any animal language, which animal's language would you choose?",
                "What's the most absurd thing you've ever seen someone do in public?",
                "If you had to wear one hat for the rest of your life, what kind of hat would it be?",
                "Would you rather fight one horse-sized duck or one hundred duck-sized horses?",
                "If you could have any object instantly appear whenever you needed it (and disappear when not needed), what would it be?",
                "If you had to communicate only through interpretive dance for a week, what message would you struggle to convey?",
                "What's the strangest thing you've ever eaten and surprisingly enjoyed?",
                "Would you rather have knees that bend both ways or elbows that bend both ways?",
                "If animals could talk, which species would be the rudest?",
                "What's a mundane superpower you'd actually find incredibly useful in daily life?",
                "If you could replace handshakes with any other greeting, what would it be?",
                "Would you rather have constantly itchy feet or constantly sticky hands?",
                "If you woke up tomorrow with the ability to talk to inanimate objects, which object would you speak to first?",
                "What's the most unusual item you have in your fridge right now?",
                "If you had to wear a ridiculous costume every day for a month, what would it be?",
                "Would you rather have a perpetually squeaky voice or always smell faintly of onions?",
                "If you could swap bodies with any fictional creature for a day, which one?",
                "What's the silliest argument you've ever overheard?",
                "If you could only eat one colour of food for a year, which colour would you choose?",
                "Would you rather have a tiny, annoying bell ring every time you yawn, or a small puff of glitter explode every time you sneeze?",
                "If you could have any animal as your personal assistant, which animal would you choose and why?",
                "What's the most ridiculous thing you've ever spent money on?",
                "If your pet could suddenly speak, what's the first thing you think it would say?",
                "Would you rather be able to fly but only at walking pace, or be invisible but only when no one is looking?",
                "What's the most bizarre dream you've ever had?",
                "If you had a personal theme song that played whenever you entered a room, what would it be?",
                "Would you rather always be slightly too hot or slightly too cold?",
                "If you could only communicate using emojis, what's the most complex message you'd try to send?",
                "What's a weird habit you have that you're sure no one else does?",
                "If you could rename yourself using only two words, what would they be?",
                "Would you rather have to wear a giant foam finger for the rest of your life or have permanent clown shoes?",
                "If you could choose any fictional food to be real, what would it be?",
                "What's the most unusual piece of advice you've ever been given?",
                "Would you rather be able to understand squirrels or pigeons?",
                "If you had to trade your sense of taste for an enhanced sense of smell, would you do it?",
                "What's the strangest thing you've seen someone do while driving?",
                "If you could only watch one TV show for the rest of your life, what would it be?",
                "Would you rather be famous for something ridiculous or infamous for something slightly embarrassing?",
                "If you could only eat condiments for a week, which one would you choose to survive on?",
                "What's your most irrational fear?",
                "If you had a warning label, what would it say?",
                "Would you rather have perpetually cold coffee or perpetually lukewarm tea?",
                "If you could only speak in movie quotes for a day, which film would you choose to quote from?",
                "What's the most ridiculous thing you've convinced someone of?",
                "If you could have an emoji for every single emotion, which new ones would you create?",
                "Would you rather have a permanent case of the giggles or perpetually have to wink at people?",
                "What's the most unusual item you carry in your bag/pockets?",
                "If you could replace your bed with any other object, what would it be?",
                "Would you rather be followed everywhere by a marching band or have a personal laugh track every time you made a joke?",
                "What's the most outlandish rumour you've ever heard about yourself?",
                "If you could only use one kitchen utensil for cooking everything, which one?",
                "Would you rather have to smell everything intensely or hear everything intensely?",
                "If you could high-five any historical figure, who would it be?",
                "What's the silliest thing you've ever done to avoid social interaction?",
                "Would you rather your only mode of transport be a unicycle or a pogo stick?",
                "If you could have a conversation with a sentient blob of jelly, what would you talk about?",
                "What's the most obscure fact you know?",
                "Would you rather have a perpetually runny nose or constantly watery eyes?",
                "If you could only wear clothes made of one material, what would it be?",
                "What's a fictional item you desperately wish was real?",
                "Would you rather be able to talk to plants or understand insects?",
                "If you had a personal jingle that played every time you entered a room, what would it be?",
                "What's the most unexpected item you've found in your own home?",
                "Would you rather have permanent marker on your face or invisible ink on your clothes that shows up in the rain?",
                "If you could only communicate through charades, what's the first thing you'd try to explain?",
                "What's the most ridiculous conspiracy theory you've ever heard?",
                "Would you rather have to bark like a dog every time you say hello, or meow like a cat every time you say goodbye?",
                "If you could have a professional wrestler as your personal bodyguard for a day, who would it be?",
                "What's the most unusual place you've ever fallen asleep?",
                "Would you rather have unlimited bacon but no games, or unlimited games but no bacon?",
                "If you could make one small, irritating noise whenever someone spoke, what would it be?",
                "What's the most bizarre piece of art you've ever seen?",
                "Would you rather lose the ability to laugh or the ability to cry?",
                "If you could only eat food shaped like animals, which animal would you eat most often?",
                "What's the most useless talent you possess?",
                "Would you rather have perpetually wet socks or perpetually tangled hair?",
                "If you could swap places with any cartoon character for a day, who would it be?",
                "What's the silliest thing you've ever done out of boredom?",
                "Would you rather live in a house made of sweets or a house made of cheese?",
                "If you could only listen to one song for the rest of your life, what would it be?",
                "What's the most outrageous lie you've ever told (and gotten away with)?",
                "Would you rather have hands for feet or feet for hands?",
                "If you could have a single, non-human companion who could understand all your thoughts, what would it be?",
                "What's the most unexpected thing you've ever found in a secondhand shop?",
                "Would you rather have to wear a tinfoil hat everywhere or a tiny propeller beanie?",
                "If you could replace one body part with a common household item, which one and what item?",
                "What's the strangest thing you've seen on public transport?",
                "Would you rather have a permanent unibrow or a permanent handlebar moustache?",
                "If you could speak to one species of mythical creature, which would it be?",
                "What's the most bizarre piece of junk mail you've ever received?",
                "Would you rather have the ability to talk to insects or control traffic lights?",
                "If you could only eat food that has been prepared by a celebrity chef, who would it be?",
                "What's the most ridiculous thing you believed as a child?",
                "Would you rather have a constant low-level static shock or always have chewing gum stuck to your shoe?",
                "If you could only drink one beverage for the rest of your life (other than water), what would it be?",
                "What's the most unusual talent you've witnessed?",
                "Would you rather be followed by a personal spotlight or a constant swarm of harmless butterflies?",
                "If you could be famous for something ridiculous, what would it be?",
                "What's the silliest thing you've ever done to make someone laugh?",
                "Would you rather have your clothes always be one size too big or one size too small?",
                "If you could only eat crunchy food or only eat soft food for a month, which would you choose?",
                "What's the most unusual item in your bedside table?",
                "Would you rather have to wear socks on your hands or gloves on your feet?",
                "If you could swap houses with any fictional character, who would it be?",
                "What's the most bizarre historical fact you know?",
                "Would you rather have a tiny unicorn or a tiny dragon as a pet?",
                "If you could only communicate using only animal noises, which animal noise would be your primary one?",
                "What's the most unexpected sound you've ever heard?",
                "Would you rather have constantly cold hands or constantly cold feet?",
                "If you could only wear one outfit for a year, what would it be?",
                "What's a fictional place that sounds utterly miserable to live in?",
                "Would you rather be able to turn invisible but only when you hold your breath, or be able to teleport but only to places you've been before?",
                "What's the silliest excuse you've ever used?",
                "Would you rather your phone only make animal sounds or your car only play children's songs?",
                "If you could have any fictional vehicle, what would it be?",
                "What's the most absurd thing you've heard someone complain about?",
                "Would you rather have perpetually slightly greasy hair or perpetually dry, flaky skin?",
                "If you could have a conversation with a talking plant, what would you talk about?",
                "What's the most unusual thing you've seen someone wear?",
                "Would you rather your tears be glitter or your sweat be syrup?",
                "If you could add one absurd feature to your home, what would it be?",
                "What's the most unusual dream job you can think of?",
                "Would you rather always have to whisper or always have to shout?",
                "If you could only eat food that begins with the first letter of your name, what would you eat?",
                "What's the most nonsensical thing someone has ever said to you?",
                "Would you rather have permanent hiccups or a permanent twitch?",
                "If you could only use one finger to type for the rest of your life, which finger would you choose?",
                "What's the most random act of kindness you've ever done?",
                "Would you rather have your feet grow one size bigger every year or your ears grow one inch longer every year?",
                "If you could swap brains with any animal for an hour, which one?",
                "What's the most bizarre thing you've ever cooked?",
                "Would you rather always be 5 minutes late or always be 20 minutes early?",
                "If you could only use one form of transport for the rest of your life, what would it be?",
                "What's the most ridiculous thing you've seen someone get angry about?",
                "Would you rather have a pet dragon the size of a cat or a pet cat the size of a dragon?",
                "If you could replace your voice with a famous sound effect, what would it be?",
                "What's the most outlandish outfit you've ever worn?",
                "Would you rather be able to talk to ghosts or see into the future (but only the next 5 minutes)?",
                "If you could only eat breakfast food for every meal, what would you eat?",
                "What's the silliest nickname you've ever had?",
                "Would you rather have super speed but only when you're walking backwards, or super strength but only when you're wearing a tutu?",
                "If you could give one absurd piece of advice to a stranger, what would it be?",
                "What's the most unexpected talent you've discovered in someone?",
                "Would you rather sneeze confetti or burp bubbles?",
                "If you could have a conversation with a fictional villain, who would it be and what would you ask?",
                "What's the most bizarre thing you've seen a customer do?",
                "Would you rather always have to wear mismatched socks or mismatched shoes?",
                "If you could only use one word for every sentence, what would it be?",
                "What's the most unusual thing you've done to cheer yourself up?",
                "Would you rather have your nose grow an inch every time you lie, or your ears turn bright green every time you're embarrassed?",
                "If you could spend a day as any object, what would it be?",
                "What's the most ridiculous song you know all the lyrics to?",
                "Would you rather live without internet or without air conditioning (or heating)?",
                "If you could have a single item from any fictional universe, what would it be?",
                "What's the most bizarre thing you've found in nature?",
                "Would you rather have a permanent singing voice, even when talking, or always hear background music wherever you go?",
                "If you could only eat food that is blue, what would your diet consist of?",
                "What's the most absurd thing you've ever had to explain?",
                "Would you rather have a tiny person living in your ear giving you life advice, or a tiny dragon on your shoulder that breathes fire when you're annoyed?",
                "If you could invent a new animal, what two existing animals would you combine?",
                "What's the silliest thing you've ever seen a grown-up do?",
                "Would you rather have every text message you send autocorrect to a random animal noise, or every email you send sign off with 'Sent from my banana'?",
                "If you could be famous for an extremely niche and bizarre talent, what would it be?",
                "What's the most random thing you've ever bought on a whim?",
                "Would you rather have perpetually slightly burnt toast or perpetually slightly soggy cereal?",
                "If you could swap lives with any cartoon villain for a day, who would it be?",
                "What's the most illogical thing you do regularly?",
                "Would you rather have a pet that can talk but always insults you, or a pet that can't talk but always looks sad?",
                "If you could add one absurd law to your country, what would it be?",
                "What's the most embarrassing thing you've ever done in front of a stranger?",
                "Would you rather have to wear a dog cone around your neck for a week or walk everywhere with a squeaky toy in your shoe?",
                "If you could only answer questions with 'yes' or 'no' for a day, how would you manage?",
                "What's the most unusual food combination you enjoy?",
                "Would you rather have extremely long eyelashes that constantly get in your way or constantly shedding hair (like a dog)?",
                "If you could have a tiny personal rain cloud that followed you everywhere, would you want it?",
                "What's the strangest piece of art you own?",
                "Would you rather your laugh sound like a honking goose or a meowing cat?",
                "If you could be in any video game, which one and what character?",
                "What's the most peculiar thing you've ever witnessed in nature?",
                "Would you rather have super sensitive hearing or super sensitive smell?",
                "If you could only wear clothes with polka dots or stripes for the rest of your life, which would you choose?",
                "What's a fictional item that would be completely useless in real life?",
                "Would you rather have perpetually cold feet or perpetually sweaty palms?",
                "If you could swap places with any inanimate object for an hour, what would it be?",
                "What's the most absurd thing you've seen on social media?",
                "Would you rather your phone battery always be at 10% or your internet always be dial-up speed?",
                "If you could only eat food that is green, what would your diet consist of?",
                "What's the most ridiculous thing you've ever heard someone try to justify?",
                "Would you rather have all streetlights turn green when you approach them or always find the exact parking spot you need?",
                "If you could be a background character in any movie, which movie and what would you be doing?",
                "What's the most nonsensical conversation you've ever had?",
                "Would you rather have a permanent glitter allergy or always smell like old cheese?",
                "If you could only use one utensil for eating for the rest of your life, what would it be?",
                "What's the most random piece of trivia you know?",
                "Would you rather have to speak in rhymes all the time or only be able to communicate through interpretive dance?",
                "If you could have a pet that is half-animal, half-object, what would it be?",
                "What's the most illogical fear you have?",
                "Would you rather have constantly tangled earphones or constantly misplaced keys?",
                "If you could be a flavour of ice cream, what would you be?",
                "What's the most absurd thing you've ever done to impress someone?",
                "Would you rather always have crumbs in your bed or always have sand in your shoes?",
                "If you could only eat food that is spicy, what would your meals look like?",
                "What's the most ridiculous purchase you've ever made that you don't regret?",
                "Would you rather have a tiny, invisible personal assistant who occasionally messes things up or a huge, visible personal assistant who is perfectly efficient but constantly judges you?",
                "If you could invent a new Olympic sport, what would it be?",
                "What's the most unusual thing you've ever cooked for yourself?",
                "Would you rather wear a superhero cape every day or a wizard's hat every day?",
                "If you could have a magic remote control that only affects animals, what's the first thing you'd do with it?",
                "What's the most bizarre item you've seen in someone else's home?",
                "Would you rather have your belly button be an outie or your ears be slightly pointed?",
                "If you could only listen to one album for the rest of your life, which one?",
                "What's the most ridiculous thing you've done to get out of doing something?",
                "Would you rather have to wear a bell around your neck or a tiny propeller on your head?",
                "If you could have one absurd item of clothing that changes colour with your mood, what would it be?",
                "What's the most unusual dream you've had that felt real?",
                "Would you rather always have to use a blunt pencil or always have to use a pen that occasionally runs out of ink?",
                "If you could only eat food that is purple, what would your next meal be?",
                "What's the most nonsensical job title you can imagine?",
                "Would you rather have constantly static hair or constantly smelling socks?",
                "If you could swap places with any fictional sidekick for a day, who would it be?",
                "What's the most random thing you've ever found in your pocket?",
                "Would you rather have a small, harmless alien companion who only communicates through interpretive dance or a pet parrot who only repeats your most embarrassing moments?",
                "If you could add one absurd rule to a common game, what would it be?",
                "What's the silliest thing you've ever done to impress a crush?",
                "Would you rather your feet randomly tap dance or your hands spontaneously mime things?",
                "If you could only listen to elevator music or polka music for the rest of your life, which would you choose?",
                "What's the most outrageous thing you've ever witnessed at a party?",
                "Would you rather be able to jump incredibly high but have no control over landing, or be able to run incredibly fast but only on your hands and knees?",
                "If you could turn any common object into a musical instrument, what would it be and what would it sound like?",
                "What's the most unusual item you've ever seen a tourist buy?",
                "Would you rather your sneezes sound like a trumpet or your yawns sound like a foghorn?",
                "If you could have any fictional animal as your housemate, which one?",
                "What's the most bizarre thing you've ever seen advertised?",
                "Would you rather have permanent bed head or permanent hat hair?",
                "If you could replace your reflection with any fictional character's reflection, who would it be?",
                "What's the most ridiculous thing you've ever done for a dare?",
                "Would you rather only be able to speak in riddles or only be able to speak in rhymes?",
                "If you could add one absurd flavour to every food, what would it be?",
                "What's the most unconvincing lie you've ever heard?",
                "Would you rather have super strength but only when naked, or super speed but only when wearing roller skates?",
                "If you could only eat food that is crunchy, what would your next meal be?",
                "What's the most nonsensical question you've ever been asked?",
                "Would you rather have your shadow be a different colour every day or always be trailed by a single, enthusiastic pigeon?",
                "If you could only wear one type of footwear for the rest of your life, what would it be?",
                "What's the most random piece of clothing you own?",
                "Would you rather have to give a dramatic monologue every time you introduced yourself or perform a small magic trick every time you finished a conversation?",
                "If you could replace your nose with any other object, what would it be?",
                "What's the most absurd thing you've ever laughed at?",
                "Would you rather have perpetually slightly greasy hair or perpetually dry, flaky skin?",
                "If you could have a conversation with a talking piece of toast, what would you ask it?",
                "What's the most unusual gift you've ever received?",
                "Would you rather your thoughts were broadcast as a loud whisper or your dreams were acted out by puppets on a small stage near you every night?",
                "If you could only eat food that is red, what would your diet consist of?",
                "What's the most illogical fashion trend you've ever seen?",
                "Would you rather have a permanent tiny cloud raining on your head or always have a gust of wind blowing in your face?",
                "If you could be a famous meme for a day, which one?",
                "What's the most bizarre piece of advice you've ever given?",
                "Would you rather have to wear a bell on your ear or a small propeller on your head?",
                "If you could only drink beverages that are fizzy, what would you drink?",
                "What's the most nonsensical product you've ever seen for sale?",
                "Would you rather have a tiny, annoying personal narrator describe your every move or have a personal soundtrack that changes inappropriately with your mood?",
                "If you could invent a new holiday, what completely absurd activity would be mandatory?",
                "What's the silliest thing you've ever seen a pet do?",
                "Would you rather communicate only through a series of elaborate hand gestures or only through singing opera?",
                "If you could swap places with any cartoon character, who would it be and what would be the first thing you'd do?",
                "What's the most unexpected thing you've learned about your family?",
                "Would you rather have an incredibly loud internal monologue that everyone can hear or never be able to speak above a whisper?",
                "If you could replace your fingernails with any other common household item, what would they be?",
                "What's the most absurd thing you've ever seen a grown-up collect?",
                "Would you rather have a permanent tiny crown stuck to your head or perpetually wear a tiny monocle?",
                "If you could only eat food that floats, what would your diet consist of?",
                "What's the most illogical thing you've heard someone say in a serious conversation?",
                "Would you rather have super strength but only when standing on one leg, or super speed but only when crawling?",
                "If you could be a flavour of crisps, what would you be?",
                "What's the most random thing that always makes you laugh?",
                "Would you rather have perpetually damp hair or perpetually cold feet?",
                "If you could have any fictional animal as a co-worker, which one?",
                "What's the silliest mistake you've ever made at work?",
                "Would you rather have a perpetually broken umbrella or perpetually untied shoelaces?",
                "If you could only eat food that is smooth, what would your next meal be?",
                "What's the most ridiculous thing you've ever seen someone do for attention?",
                "Would you rather have a personal cloud of glitter follow you everywhere or have your clothes occasionally burst into harmless, temporary flames?",
                "If you could communicate with one type of household appliance, which one?",
                "What's the most unusual souvenir you own?",
                "Would you rather your sneezes sound like a foghorn or your burps sound like a cow mooing?",
                "If you could have any fictional object that's entirely useless, what would it be?",
                "What's the most bizarre thing you've ever seen happen on a bus?",
                "Would you rather have permanent stripes or permanent polka dots on your skin?",
                "If you could replace one of your five senses with an animal's sense, which one and what animal?",
                "What's the most outlandish theory you secretly believe?",
                "Would you rather always have to wear a tiny hat or always carry a tiny umbrella?",
                "If you could only drink one liquid for the rest of your life (other than water), what would it be?",
                "What's the most nonsensical question you've ever been asked that made you truly ponder?",
                "Would you rather have a permanent faint rainbow appear over your head or constantly emit the smell of freshly baked bread?",
                "If you could be a famous fictional character's sidekick, who would you be?",
                "What's the most random thing you've ever collected?",
                "Would you rather have perpetually cold coffee or perpetually lukewarm tea?",
                "If you could only speak in a certain accent for the rest of your life, which one?",
                "What's the most peculiar dream you've had that you still remember vividly?",
                "Would you rather have a constantly itchy nose or perpetually chapped lips?",
                "If you could only wear shoes that are too big or too small, which would you choose?",
                "What's the most absurd thing you've ever convinced a child is real?",
                "Would you rather have your phone only play elevator music or your doorbell play a full operatic aria?",
                "If you could swap bodies with any historical figure for a day, who would it be and what's the first mundane thing you'd do?",
                "What's the most illogical thing you've ever seen someone passionately argue about?",
                "Would you rather have a tiny, harmless ghost that follows you everywhere or a friendly, invisible dragon that only you can see?",
                "If you could add one absurd item to every grocery basket, what would it be?",
                "What's the silliest thing you've ever worn to a formal event?",
                "Would you rather always speak in a whisper or always speak in a booming theatrical voice?",
                "If you could only eat food that is yellow, what would your diet consist of?",
                "What's the most nonsensical piece of advice you've ever been given?",
                "Would you rather have permanent glitter in your hair or constantly feel like you're walking on bouncy castles?",
                "If you could be a sound effect, what would you be?",
                "What's the most random thing you've ever learned that has no practical use?",
                "Would you rather have your internal monologue be sung by a choir or performed as a dramatic reading?",
                "If you could replace one of your limbs with a spring, which one and why?",
                "What's the most bizarre thing you've ever seen at a wedding?",
                "Would you rather have to clap your hands three times before speaking or click your heels together before walking?",
                "If you could be any flavour of chewing gum, what would you be?",
                "What's the most illogical thing you've ever done to save a small amount of money?",
                "Would you rather always know exactly what someone is thinking (even if you don't want to know) or always be able to perfectly mimic any sound you hear?",
                "If you could add one absurd rule to the workplace, what would it be?",
                "What's the silliest thing you've ever done to cheer up a friend?",
                "Would you rather have a permanent case of static cling or perpetually have one ear slightly louder than the other?",
                "If you could only eat food that is crispy, what would your next meal be?",
                "What's the most absurd reason you've ever been late?",
                "Would you rather have a tiny, invisible personal fanfare play every time you successfully complete a task, or a tiny, invisible personal clown juggle behind you when you're stressed?",
                "If you could be a character in any children's book, who would you be?",
                "What's the most unusual place you've ever napped?",
                "Would you rather have to sing all your sentences or rhyme all your sentences?",
                "If you could change one minor physical feature about yourself to something absurd, what would it be?",
                "What's the most random item you own that you can't explain why you have?",
                "Would you rather have to wear a ridiculous hat everywhere or always have a clown nose?",
                "If you could swap houses with any fictional animal, which one?",
                "What's the most unexpected gift you've ever received?",
                "Would you rather your sneezes sound like a duck quack or your burps sound like a car horn?",
                "If you could only eat food that is circular, what would your diet consist of?",
                "What's the most illogical thing you've ever tried to fix?",
                "Would you rather have perpetually slightly sticky fingers or perpetually slightly itchy elbows?",
                "If you could be a type of biscuit, what would you be?",
                "What's the silliest reason you've ever given for not wanting to do something?",
                "Would you rather live in a world where everyone always told the truth (no filter) or a world where everyone always spoke in rhymes?",
                "If you could have any fictional animal as a pet that is perfectly behaved and lives forever, what would it be?",
                "What's the most unexpected place you've ever heard your favourite song?",
                "Would you rather have your feet randomly tap dance when you're stressed or have your nose light up when you're excited?",
                "If you could choose any absurd item to always carry with you, what would it be?",
                "What's the most bizarre thing you've seen a human try to eat?",
                "Would you rather have your voice change pitch randomly or always be accompanied by faint accordion music?",
                "If you could be a flavour of ice cream, what would you be?",
                "What's the most illogical thing you've ever done out of laziness?",
                "Would you rather have permanent googly eyes on your eyelids or always have a small, harmless mushroom growing on your head?",
                "If you could invent a new colour that only you could see, what would it look like?",
                "What's the most random celebrity encounter you've had that felt like a dream?",
                "Would you rather always wear clothes that are slightly damp or always wear clothes that are slightly too tight?",
                "If you could only eat food that is salty, what would your meals look like?",
                "What's the most nonsensical piece of advice you've ever given?",
                "Would you rather have super long hair that constantly gets tangled or super short hair that constantly needs trimming?",
                "If you could be a type of cloud, what would you be?",
                "What's the most unusual place you've ever found a lost item?",
                "Would you rather your laugh sound like a honking car horn or a squeaking mouse?",
                "If you could have any fictional plant that's real, what would it be?",
                "What's the most bizarre thing you've ever seen happen at a formal event?",
                "Would you rather have permanent glitter stuck to your face or always smell faintly of cabbage?",
                "If you could replace your hands with any other objects, what would they be?",
                "What's the most ridiculous thing you've ever attempted to fix with duct tape?",
                "Would you rather always have to wear a brightly coloured feather boa or always have to wear oversized novelty glasses?",
                "If you could only communicate using only animal noises for a month, which animal noise would you choose to express anger?",
                "What's the most unexpected skill you've learned from a TV show?",
                "Would you rather your phone only take blurry photos or your computer only run at dial-up speed?",
                "If you could be a flavour of chocolate, what would you be?",
                "What's the most nonsensical argument you've ever had?",
                "Would you rather have a permanent mild itch you can't scratch or always feel like you've just walked through a spiderweb?",
                "If you could only use one social media platform for the rest of your life, which one?",
                "What's the most random item you have in your car?",
                "Would you rather have your shoes constantly untie themselves or your pockets always have holes?",
                "If you could be a type of crisps, what flavour?",
                "What's the silliest thing you've ever lost?",
                "Would you rather live in a house where the doors randomly swap positions or the stairs randomly change height?",
                "If you could have any mythical creature as your roommate, which one?",
                "What's the most unexpected thing you've cooked that turned out amazing?",
                "Would you rather your singing voice be replaced by a kazoo or your speaking voice be autotuned?",
                "If you could change one minor bodily function to something absurd and harmless, what would it be?",
                "What's the most random thing you've ever found in your own pockets?",
                "Would you rather have to wear a ridiculous hat everywhere or always have a tiny, harmless bird nesting in your hair?",
                "If you could swap houses with any fictional character for a week and do something mundane, who would it be and what would you do?",
                "What's the most absurd thing you've overheard someone complaining about that was genuinely serious?",
                "Would you rather your sneezes shoot out small, harmless glitter or your burps emit a tiny, harmless puff of smoke?",
                "If you could add one absurd item to every single meal you eat, but it's delicious, what would it be?",
                "What's the most illogical thing you've ever seen someone do when they thought no one was watching, but they were wrong?",
                "Would you rather have a permanent mild itch on your back that you can't reach or perpetually feel like you have an eyelash in your eye?",
                "If you could be a type of sweet, what would you be?",
                "What's the silliest thing you've ever done to avoid a social gathering?",
                "Would you rather live in a world where everyone communicates only through interpretive dance or a world where everyone always speaks in whispers?",
                "If you could have any absurd superpower that only works on inanimate objects, what would it be?",
                "What's the most random item you've seen someone use as a makeshift tool?",
                "Would you rather have your hands randomly make a 'boing' sound when you move them or your feet make a 'squeak' sound when you walk?",
                "If you could be a flavour of soup that makes people uncontrollably laugh, what would it be?",
                "What's the most absurd dream you've had that you genuinely believed was real for a moment after waking?",
                "Would you rather have a permanent faint smell of old socks or perpetually feel like your hair is slightly damp?",
                "If you could only wear one type of footwear for the rest of your life, even if it's inappropriate, what would it be?",
                "What's the most random piece of advice you've ever received that ended up being surprisingly useful?",
                "Would you rather have your shadow always be a cartoon character or your reflection occasionally wink and give you a thumbs up?",
                "If you could only drink beverages that are green, what would you drink?",
                "What's the most peculiar thing you've ever seen someone doing in public at night?",
                "Would you rather your laugh sound like a honking clown horn or a tiny, persistent whimper?",
                "If you could have any fictional plant as a pet, but it constantly needs encouraging words, what would it be?",
                "What's the most bizarre thing you've ever seen at a traffic light?",
                "Would you rather have permanent glitter eyebrows or always smell faintly of burnt popcorn?",
                "If you could replace one of your limbs with a common household appliance, which one and what appliance?",
                "What's the most ridiculous thing you've ever lost and then found in a place that made perfect sense?",
                "Would you rather always speak in a high-pitched squeak or a low, rumbling growl?",
                "If you could only eat food that is striped, what would your meals consist of?",
                "What's the most illogical thing you've ever seen someone genuinely get angry about?",
                "Would you rather have super strength but only when balancing a spoon on your nose, or super speed but only when wearing roller skates indoors?",
                "If you could be a flavour of ice cream that can never melt, what absurd flavour would you be?",
                "What's the silliest reason you've ever given for wanting a new gadget?",
                "Would you rather live in a world where everyone communicates only through mime or a world where everyone always sings?",
                "If you could have any absurd superpower that only works on fruit, what would it be?",
                "What's the most random item you've seen someone use as a weapon (non-harmful)?",
                "Would you rather have your hands randomly make a 'honk' sound when you move them or your feet make a 'meow' sound when you walk?",
                "If you could be a type of bread that makes people sing whenever they eat it, what would it be?",
                "What's the most illogical thing you've ever seen someone try to cook without a recipe?",
                "Would you rather always know when someone is lying (but they also know you know) or always be able to perfectly mimic any voice you hear?",
                "If you could add one absurd, non-harmful feature to all public bathrooms, what would it be?",
                "What's the silliest thing you've ever done to get out of a tedious task?",
                "Would you rather have a permanent mild itch on your nose that you can't scratch or perpetually feel like you have an invisible feather tickling your ear?",
                "If you could be a type of crisps that has a surprising and delightful flavour, what would it be?",
                "What's the most absurd dream you've had that involved a talking animal?",
                "Would you rather have perpetually slightly undercooked vegetables or perpetually slightly burnt toast?",
                "If you could only eat food that is yellow, what would your next meal be?",
                "What's the most nonsensical job you can imagine that pays really well?",
                "Would you rather have permanent static hair or perpetually feel like you have a piece of fluff stuck to your tongue?",
                "If you could be a piece of stationery that constantly giggles, what would it be?",
                "What's the silliest thing you've ever done just to get a reaction?",
                "Would you rather your laugh sound like a rubber chicken or your burps sound like a dramatic opera crescendo?",
                "If you could have any fictional object that's entirely useless but very shiny, what would it be?",
                "What's the most bizarre thing you've ever seen on a billboard?",
                "Would you rather have permanent slightly wonky eyes or permanent slightly wobbly knees?",
                "If you could replace one of your five senses with an animal's sense (and it's a completely absurd one), which one and what animal?",
                "What's the most outlandish conspiracy theory you've ever heard that you secretly find entertaining?",
                "Would you rather always have to wear a tiny hat that plays jaunty music or always carry a tiny, singing gnome in your pocket?",
                "If you could only eat food that has stripes, what would your diet consist of?",
                "What's the most nonsensical thing you've ever said that someone took seriously?",
                "Would you rather have a permanent faint smell of old socks or perpetually feel like you have an invisible piece of string tickling your nose?",
                "If you could be a type of weather phenomenon that makes absurd noises, what would it be?",
                "What's the most random thing you've ever bought from a vending machine?",
                "Would you rather your sneezes sound like a trumpet or your yawns sound like a foghorn?",
                "If you could have any fictional plant as a pet, but it constantly needs telling jokes to survive, what would it be?",
                "What's the most bizarre thing you've ever seen happen at a wedding?",
                "Would you rather have permanent glitter eyebrows or always smell faintly of cabbage?",
                "If you could replace your ears with any other common object, what would they be?",
                "What's the most ridiculous thing you've ever lost and never found, but still occasionally search for?",
                "Would you rather always have to speak in a high-pitched squeak or a low, rumbling growl?",
        ]
    },
    "game_pre_analytical": {
        "title": "Pre-analytical Pitfalls",
        "intro": "Identify common errors in sample collection and handling, and understand their impact on test results.",
        "questions": [ { "question": "A blood sample for **Potassium** measurement was left at room temperature...", "options": [], "explanation": "Prolonged contact of serum/plasma with red blood cells..." } ]
    },
    "game_transfusion": {
        "title": "Antibody Identification Challenge",
        "intro": "An antibody screen was positive. Use all available information to identify the antibody/antibodies present.",
        "antigens": ["D", "C", "E", "c", "e"],
        "scenarios": { "easy": [], "medium": [], "hard": [], "auto": [] }
    },
    "game_tube_sorter": {
        "title": "Specimen Reception: Tube Sorter",
        "intro": "A test name will appear. Choose the correct department or sample type.",
        "tests": [ { "name": "17-OH-progesterone", "department": "Clinical Biochemistry", "sampleType": "Plain serum (red top)" } ]
    },
    "neqas_case_2406BF1": {
        "title": "Digital Morphology Case Library",
        "case_id": "2406BF1",
        "patient_info": "24-year-old male.",
        "initial_fbc": { "Hb": "85 g/L", "WBC": "18.1 x10⁹/L", "Platelets": "357 x10⁹/L" },
        "full_fbc": { "RBC": "2.73 x10¹²/L", "Hct": "0.241 L/L" },
        "biochemistry": { "Bilirubin": "52 µmol/L", "Adjusted Calcium": "2.34 mmol/L" },
        "hplc": { "Hb F": "6.5%", "Hb A2": "4.1%", "Hb S": "85.2%" },
        "expert_commentary": "It was fairly clear from the film that this was some form of sickle cell disease...",
        "peer_features": [ { "feature": "Eosinophilia", "count": 435 }, { "feature": "Sickle Cells", "count": 428 } ],
        "morphology_features": { "Red Cell Features": ["Microcytes", "Hypochromic Cells"], "White Cell Features": ["Eosinophilia", "Band Form Neutrophils"], "Platelet Features": ["Thrombocytosis", "Large/Giant Platelets"] }
    }
            };
