const SGC_DATA = {
  "members": [
    { "name": "Michael Ellingham", "department": "Haematology & Blood Transfusion", "email": "Michael.ellingham@nhs.net" },
    { "name": "Katarzyna Fijalkowska", "department": "Haematology & Blood Transfusion", "email": "katarzyna.fijalkowska@nhs.net" },
    { "name": "Akwasi Boakye", "department": "Immunology", "email": "akwasi.boakye1@nhs.net" },
    { "name": "Yasmin Dixon", "department": "Chemistry", "email": "yasmin.dixon1@nhs.net" },
    { "name": "Matthew Rodgers", "department": "Chemistry", "email": "matthew.rodgers6@nhs.net" }
  ],
  "learningLinks": {
    "general": [
      { "name": "IBMS", "url": "https://www.ibms.org/home/", "description": "The Institute of Biomedical Science - our professional body." },
      { "name": "HCPC", "url": "https://www.hcpc-uk.org/", "description": "The Health and Care Professions Council - our regulator." },
      { "name": "RCPath", "url": "https://www.rcpath.org/", "description": "The Royal College of Pathologists." },
      { "name": "UKAS", "url": "https://www.ukas.com/", "description": "The UK's National Accreditation Body." },
      { "name": "NICE", "url": "https://www.nice.org.uk/", "description": "National Institute for Health and Care Excellence guidelines." }
    ],
    "haematology": [
      { "name": "British Society for Haematology", "url": "https://b-s-h.org.uk/", "description": "Guidelines, research and education for haematology." },
      { "name": "Haembase", "url": "https://haembase.com/", "description": "An educational resource for trainees in haematology." },
      { "name": "Bloodline Image Atlas", "url": "http://www.bloodline.net/", "description": "Image atlas and case studies for haematology." },
      { "name": "Blood Academy", "url": "https://www.blood-academy.com/", "description": "E-learning resource covering all aspects of haematology." },
      { "name": "Practical-Haemostasis", "url": "https://practical-haemostasis.com/", "description": "A guide to laboratory haemostasis and thrombosis." }
    ],
    "transfusion": [
      { "name": "Transfusion Guidelines (JPAC)", "url": "https://www.transfusionguidelines.org/", "description": "The official UK guidelines for blood transfusion services." },
      { "name": "NHS Blood and Transplant (Hospitals)", "url": "https://hospital.blood.co.uk/", "description": "Professional resources and guidelines for transfusion." },
      { "name": "SHOT", "url": "https://www.shotuk.org/", "description": "The UK's haemovigilance scheme for transfusion safety." },
      { "name": "British Blood Transfusion Society", "url": "https://www.bbts.org.uk/education/", "description": "Education, training and resources from the BBTS." },
      { "name": "Blood Bank Guy", "url": "https://www.bbguy.org/", "description": "Transfusion medicine education from Dr. Joe Chaffin." }
    ],
    "chemistry": [
      { "name": "Association for Laboratory Medicine", "url": "https://labmed.org.uk/", "description": "Formerly the ACB, a key professional body for the field." },
      { "name": "Lab Tests Online UK", "url": "https://labtestsonline.org.uk/", "description": "Peer-reviewed information on clinical lab testing." },
      { "name": "ACP Trainee Handbook", "url": "https://www.acp.org.uk/publication/books/item/clinical-biochemistry-for-trainees.html", "description": "A Clinical Biochemistry handbook from the Association of Clinical Pathologists." },
      { "name": "NHS Learning Hub - Biochemistry", "url": "https://learninghub.nhs.uk/catalogue/clinical-biochemistry-e-learning", "description": "E-learning modules covering various aspects of clinical biochemistry." },
      { "name": "The Biochemical Society", "url": "https://www.biochemistry.org/", "description": "Promoting the advancement of molecular biosciences." }
    ],
    "immunology": [
      { "name": "British Society for Immunology", "url": "https://www.immunology.org/", "description": "Representing scientists and clinicians in immunology." },
      { "name": "UK PIN", "url": "https://www.ukpin.org.uk/", "description": "The UK Primary Immunodeficiency Network." },
      { "name": "NHS Learning Hub - Immunology", "url": "https://learninghub.nhs.uk/catalogue/pathologyportal?nodeId=2196", "description": "The Pathology Portal for Immunology and Allergy." },
      { "name": "Immunology Disease Area", "url": "https://www.immunologyda.com/", "description": "Resources and news for immunology professionals." }
    ]
  },
  "rejectionReasons": {
    "haemolysed": { "title": "Haemolysed Sample", "icon": "droplet", "causes": ["Difficult venepuncture (e.g., probing for a vein, slow draw).","Using too fine a needle (<23g) for the vein, causing excessive shear stress on red cells.","Forcefully expelling blood from a syringe into a vacuum tube.","Vigorous shaking of the sample tube instead of gentle inversion.","Leaving a tourniquet on for an extended period (>1 minute), causing venous stasis.","Contamination with water, alcohol, or other chemicals from the skin or equipment.","Extreme temperatures during transport (freezing or overheating).","Patient conditions causing fragile red cells (e.g., some haemolytic anaemias)."], "prevention": ["Ensure a smooth, clean venepuncture with a good blood flow. Anchor the vein well.","Use an appropriate gauge needle (21g is standard for adults).","If using a syringe, pull the plunger back slowly and steadily.","When transferring from a syringe, remove the needle and the tube cap, and allow blood to run gently down the side of the tube.","Gently invert tubes the required number of times (e.g., 8-10 for EDTA); do NOT shake.","Release the tourniquet as soon as blood flow is established.","Ensure the venepuncture site is completely dry after cleaning.","Transport samples at ambient temperature unless otherwise specified."], "impact": "Haemolysis releases intracellular components into the plasma/serum. This falsely elevates results for Potassium, LDH, AST, and Magnesium, potentially leading to incorrect diagnosis and inappropriate treatment. It can also interfere with many other chemistry and immunoassay tests, rendering the sample useless." },
    "clotted": { "title": "Clotted Sample", "icon": "grid", "causes": ["Insufficient or delayed mixing of anticoagulant tubes (e.g., EDTA, Citrate).","Slow blood collection, allowing the clotting cascade to begin before mixing.","Incorrect order of draw (e.g., drawing a serum tube before a citrate tube can cause additive carryover).","Patient has a very high platelet count or is hypercoagulable.","Difficult draw causing tissue factor activation in the sample."], "prevention": ["Gently invert anticoagulant tubes 8-10 times immediately after collection. This is the single most important step.","Ensure a swift, clean collection once the vein is punctured.","Follow the correct order of draw: Blood cultures, Citrate (blue), Serum (gold/red), Heparin (green), EDTA (purple), Fluoride (grey).","Be aware of patient status and ensure thorough mixing for those with high platelet counts.","If the draw is slow, be extra vigilant with immediate mixing."], "impact": "Clots consume platelets and clotting factors, making FBC and coagulation results completely inaccurate and unreliable. Small, unnoticed clots can block the probes on laboratory analysers, causing instrument downtime and delaying other patient results." },
    "insufficient": { "title": "Insufficient Sample (QNS)", "icon": "minus-circle", "causes": ["Vein collapsing during the draw.","Losing the position of the needle in the vein part-way through collection.","Patient has difficult venous access (e.g., small, fragile, or deep veins).","Incorrect tube chosen for the tests requested (e.g., needing to fill multiple tubes from one draw).","Loss of vacuum in the collection tube."], "prevention": ["Plan the collection: know what tubes are needed and have them ready.","Use appropriate techniques for difficult access (e.g., a butterfly needle may provide better control).","Anchor the vein securely to prevent it from rolling.","For citrate (blue top) tubes, it is CRITICAL that the tube is filled to the mark to maintain the correct 9:1 blood-to-anticoagulant ratio. An underfilled tube will be rejected for all coagulation testing."], "impact": "An insufficient sample means not all requested tests can be performed. For coagulation tubes, the wrong blood-to-anticoagulant ratio makes results invalid. For all samples, it necessitates a redraw, causing delays in diagnosis and treatment, and a poor experience for the patient." },
    "mislabeled": { "title": "Mislabeled / Unlabeled Sample", "icon": "user-x", "causes": ["Sample was not labelled at the patient's bedside immediately after collection.","Pre-labelling tubes before the draw.","Incorrect patient details used (e.g., from another patient's notes).","Label is illegible, damaged, or has incomplete information.","Discrepancy between the sample label and the request form details."], "prevention": ["The GOLDEN RULE: ALWAYS label the tube immediately after collection, at the patient's side.","Confirm patient identity using at least two unique identifiers (e.g., full name and date of birth) verbally and by checking their wristband.","Never pre-label tubes away from the patient.","Ensure handwriting is clear and the label is securely attached without obscuring the sample window.","Cross-reference all details with the request form before sending the sample to the lab."], "impact": "This is the most serious type of pre-analytical error. A mislabeled sample could lead to a catastrophic outcome for a patient, such as receiving the wrong blood type in a transfusion. The laboratory has a zero-tolerance policy for mislabeled or unlabeled samples; they will always be rejected to ensure patient safety." },
    "wrong_tube": { "title": "Wrong Tube Type", "icon": "refresh-cw", "causes": ["Lack of familiarity with the tests required and the corresponding tube colours.","Accidentally picking up the wrong tube from the trolley.","Not checking the departmental handbook or test directory before collection."], "prevention": ["Always confirm the correct tube type for the requested tests before venepuncture. Use a guide if unsure.","Example: Chemistry (U&Es, LFTs) needs a serum (gold top) or heparin (green top) tube. Sending an EDTA (purple top) is wrong because the EDTA chelates calcium, making the calcium result falsely zero and the potassium result falsely very high.","Example: Coagulation tests (PT, APTT) MUST be in a citrate (light blue top) tube.","Organise your collection trolley to keep different tube types clearly separated."], "impact": "The additives in each tube are specific for the tests being performed. Using the wrong tube will lead to completely erroneous results or will make the analysis impossible. The sample will always be rejected, requiring a patient redraw." },
    "delay_transit": { "title": "Delay in Transit / Old Sample", "icon": "clock", "causes": ["Sample not sent to the laboratory promptly after collection.","Sample left on a ward trolley or in a collection point for an extended period.","Transport delays from off-site locations.","Forgetting to arrange for a sample to be sent to the lab."], "prevention": ["Send all samples to the laboratory as soon as possible after collection via the pneumatic tube system or portering service.","Have a clear process for ensuring samples collected are dispatched promptly.","For specific time-sensitive tests (e.g., Ammonia, ACTH), the lab must be pre-alerted and the sample sent immediately on ice."], "impact": "Many analytes are unstable. Delays can cause falsely high potassium levels (as it leaks from red cells), falsely low glucose levels (as it is consumed by cells), and degradation of clotting factors, making results unreliable. The sample will be rejected if it is too old for the requested tests." }
  }
};
